import config from 'config';
import nock from 'nock';

export default function() {
  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'card[number]=4242424242424242&card[exp_month]=12&card[exp_year]=2028&card[cvc]=222')
    .reply(
      200,
      {
        id: 'tok_1E9DUoDjPFcHOcTmX5xxwNSg',
        object: 'token',
        card: {
          id: 'card_1E9DUoDjPFcHOcTmCEH4mx9p',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'unchecked',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: 'ftgJeBXvQSZ4HMCg',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454918,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:41:58 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '785',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_EQBC2367jeRrvm',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://www.gravatar.com:443', { encodedQueryParams: true })
    .get('/avatar/9cbcedbd240587a8a6620e3ed5118829')
    .query({ default: '404' })
    .reply(404, '404 Not Found', [
      'Server',
      'nginx',
      'Date',
      'Fri, 01 Mar 2019 15:39:54 GMT',
      'Content-Type',
      'text/html; charset=utf-8',
      'Content-Length',
      '13',
      'Connection',
      'close',
      'Last-Modified',
      'Wed, 11 Jan 1984 08:00:00 GMT',
      'Link',
      '<https://www.gravatar.com/avatar/9cbcedbd240587a8a6620e3ed5118829?default=404>; rel="canonical"',
      'Access-Control-Allow-Origin',
      '*',
      'ETag',
      '"404"',
      'X-nc',
      'HIT fra 2',
      'Cache-Control',
      'max-age=300',
      'Expires',
      'Fri, 01 Mar 2019 15:44:54 GMT',
      'Source-Age',
      '1435',
    ]);

  nock('https://www.gravatar.com:443', { encodedQueryParams: true })
    .get('/avatar/c31063b4d99c96a75d4f7f9dd2bb8dc7')
    .query({ default: '404' })
    .reply(404, '404 Not Found', [
      'Server',
      'nginx',
      'Date',
      'Fri, 01 Mar 2019 15:39:54 GMT',
      'Content-Type',
      'text/html; charset=utf-8',
      'Content-Length',
      '13',
      'Connection',
      'close',
      'Last-Modified',
      'Wed, 11 Jan 1984 08:00:00 GMT',
      'Link',
      '<https://www.gravatar.com/avatar/c31063b4d99c96a75d4f7f9dd2bb8dc7?default=404>; rel="canonical"',
      'Access-Control-Allow-Origin',
      '*',
      'ETag',
      '"404"',
      'X-nc',
      'HIT fra 4',
      'Cache-Control',
      'max-age=300',
      'Expires',
      'Fri, 01 Mar 2019 15:44:54 GMT',
      'Source-Age',
      '1435',
    ]);

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'card[number]=4242424242424242&card[exp_month]=12&card[exp_year]=2028&card[cvc]=222')
    .reply(
      200,
      {
        id: 'tok_1E9DUpDjPFcHOcTmDNIXRcsl',
        object: 'token',
        card: {
          id: 'card_1E9DUpDjPFcHOcTm6HMf3mjQ',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'unchecked',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: 'ftgJeBXvQSZ4HMCg',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454919,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:41:59 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '785',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_bRBIfM5O0cLdlB',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://data.fixer.io', { encodedQueryParams: true })
    .get('/latest')
    .query({ access_key: config.fixer.accessKey, base: 'USD', symbols: 'EUR' })
    .reply(200, { success: true, timestamp: 1551453127, base: 'USD', date: '2019-03-01', rates: { EUR: 0.877445 } }, [
      'Server',
      'nginx',
      'Date',
      'Fri, 01 Mar 2019 15:41:59 GMT',
      'Content-Type',
      'application/json; Charset=UTF-8',
      'Transfer-Encoding',
      'chunked',
      'Connection',
      'close',
      'X-Apilayer-Transaction-Id',
      '87ccdd90-517c-4c1b-aa1d-5ca83c818ce9',
      'Access-Control-Allow-Methods',
      'GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS',
      'Last-Modified',
      'Fri, 01 Mar 2019 15:12:07 GMT',
      'Etag',
      '8fe890b00006894b73e5f500c93e1a65',
      'Access-Control-Allow-Origin',
      '*',
      'X-Request-Time',
      '0.074',
    ]);

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DUpDjPFcHOcTmDNIXRcsl&description=https%3A%2F%2Fopencollective.com%2Fuser2&email=user2%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPOPY2UIFhON',
        object: 'customer',
        account_balance: 0,
        created: 1551454920,
        currency: null,
        default_source: 'card_1E9DUpDjPFcHOcTm6HMf3mjQ',
        delinquent: false,
        description: 'https://opencollective.com/user2',
        discount: null,
        email: 'user2@opencollective.com',
        invoice_prefix: '4A72E75',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DUpDjPFcHOcTm6HMf3mjQ',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPOPY2UIFhON',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: 'ftgJeBXvQSZ4HMCg',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPOPY2UIFhON/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPOPY2UIFhON/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:00 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_dwCdeN2rH12P6T',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'customer=cus_EcSPOPY2UIFhON')
    .reply(
      200,
      {
        id: 'tok_1E9DUrLzdXg9xKNSm3UDWKZS',
        object: 'token',
        card: {
          id: 'card_1E9DUrLzdXg9xKNSqYPpnX5N',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454921,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:01 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '780',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_N2031htYfBkaM6',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DUrLzdXg9xKNSm3UDWKZS&description=https%3A%2F%2Fopencollective.com%2Fuser2&email=user2%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPvDnmetAKEh',
        object: 'customer',
        account_balance: 0,
        created: 1551454921,
        currency: null,
        default_source: 'card_1E9DUrLzdXg9xKNSqYPpnX5N',
        delinquent: false,
        description: 'https://opencollective.com/user2',
        discount: null,
        email: 'user2@opencollective.com',
        invoice_prefix: 'A1BC890',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DUrLzdXg9xKNSqYPpnX5N',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPvDnmetAKEh',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: '1ePEQxDFh2TKt5lo',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPvDnmetAKEh/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPvDnmetAKEh/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:01 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_nE2YPtXeLK4TAn',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/charges',
      'amount=5000&currency=USD&customer=cus_EcSPvDnmetAKEh&description=Donation%20to%20tipbox&application_fee=250&metadata[from]=http%3A%2F%2Flocalhost%3A3000%2Fuser2&metadata[to]=http%3A%2F%2Flocalhost%3A3000%2Ftipbox&metadata[customerEmail]=user2%40opencollective.com&metadata[PaymentMethodId]=3',
    )
    .reply(
      200,
      {
        id: 'ch_1E9DUsLzdXg9xKNS9gfe8xqB',
        object: 'charge',
        amount: 5000,
        amount_refunded: 0,
        application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
        application_fee: 'fee_1E9DUsLzdXg9xKNSesmpxzeu',
        application_fee_amount: 250,
        balance_transaction: 'txn_1E9DUsLzdXg9xKNSq6ZH6bmn',
        captured: true,
        created: 1551454922,
        currency: 'usd',
        customer: 'cus_EcSPvDnmetAKEh',
        description: 'Donation to tipbox',
        destination: null,
        dispute: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: null,
        livemode: false,
        metadata: {
          from: 'http://localhost:3000/user2',
          to: 'http://localhost:3000/tipbox',
          customerEmail: 'user2@opencollective.com',
          PaymentMethodId: '3',
        },
        on_behalf_of: null,
        order: null,
        outcome: {
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 27,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: null,
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/acct_18KWlTLzdXg9xKNS/ch_1E9DUsLzdXg9xKNS9gfe8xqB/rcpt_EcSPMBCFnv8eI5a3O8P77gaDjSCKXBA',
        refunded: false,
        refunds: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/charges/ch_1E9DUsLzdXg9xKNS9gfe8xqB/refunds',
        },
        review: null,
        shipping: null,
        source: {
          id: 'card_1E9DUrLzdXg9xKNSqYPpnX5N',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          customer: 'cus_EcSPvDnmetAKEh',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        source_transfer: null,
        statement_descriptor: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:02 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '2271',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_7iyMs7CITF5Rlx',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .get('/v1/balance/history/txn_1E9DUsLzdXg9xKNSq6ZH6bmn')
    .reply(
      200,
      {
        id: 'txn_1E9DUsLzdXg9xKNSq6ZH6bmn',
        object: 'balance_transaction',
        amount: 5000,
        available_on: 1551744000,
        created: 1551454922,
        currency: 'usd',
        description: 'Donation to tipbox',
        exchange_rate: null,
        fee: 425,
        fee_details: [
          {
            amount: 175,
            application: null,
            currency: 'usd',
            description: 'Stripe processing fees',
            type: 'stripe_fee',
          },
          {
            amount: 250,
            application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
            currency: 'usd',
            description: 'OpenCollective application fee',
            type: 'application_fee',
          },
        ],
        net: 4575,
        source: 'ch_1E9DUsLzdXg9xKNS9gfe8xqB',
        sourced_transfers: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/transfers?source_transaction=ch_1E9DUsLzdXg9xKNS9gfe8xqB',
        },
        status: 'pending',
        type: 'charge',
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:03 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '933',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_gUJIIykStYruXR',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DUoDjPFcHOcTmX5xxwNSg&description=https%3A%2F%2Fopencollective.com%2Fuser1&email=user1%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPHXFqn3BPu5',
        object: 'customer',
        account_balance: 0,
        created: 1551454923,
        currency: null,
        default_source: 'card_1E9DUoDjPFcHOcTmCEH4mx9p',
        delinquent: false,
        description: 'https://opencollective.com/user1',
        discount: null,
        email: 'user1@opencollective.com',
        invoice_prefix: 'EFABD4E',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DUoDjPFcHOcTmCEH4mx9p',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPHXFqn3BPu5',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: 'ftgJeBXvQSZ4HMCg',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPHXFqn3BPu5/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPHXFqn3BPu5/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:03 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_GLNBc41rNWIv8O',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'customer=cus_EcSPHXFqn3BPu5')
    .reply(
      200,
      {
        id: 'tok_1E9DUuLzdXg9xKNSzPRqeArj',
        object: 'token',
        card: {
          id: 'card_1E9DUtLzdXg9xKNSFnKPR5Gq',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454924,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:04 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '780',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_wDCPDuubISFa7v',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DUuLzdXg9xKNSzPRqeArj&description=https%3A%2F%2Fopencollective.com%2Fuser1&email=user1%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPbN4w1trfJW',
        object: 'customer',
        account_balance: 0,
        created: 1551454924,
        currency: null,
        default_source: 'card_1E9DUtLzdXg9xKNSFnKPR5Gq',
        delinquent: false,
        description: 'https://opencollective.com/user1',
        discount: null,
        email: 'user1@opencollective.com',
        invoice_prefix: 'A7BDA44',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DUtLzdXg9xKNSFnKPR5Gq',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPbN4w1trfJW',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: '1ePEQxDFh2TKt5lo',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPbN4w1trfJW/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPbN4w1trfJW/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:04 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_V7wR5SxmfcoPqo',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/charges',
      'amount=10000&currency=USD&customer=cus_EcSPbN4w1trfJW&description=Matching%202x%20user2%27s%20donation&application_fee=500&metadata[from]=http%3A%2F%2Flocalhost%3A3000%2Fuser1&metadata[to]=http%3A%2F%2Flocalhost%3A3000%2Ftipbox&metadata[customerEmail]=user1%40opencollective.com&metadata[PaymentMethodId]=2',
    )
    .reply(
      200,
      {
        id: 'ch_1E9DUuLzdXg9xKNSwDtK3zvU',
        object: 'charge',
        amount: 10000,
        amount_refunded: 0,
        application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
        application_fee: 'fee_1E9DUvLzdXg9xKNS8hvxDHbO',
        application_fee_amount: 500,
        balance_transaction: 'txn_1E9DUvLzdXg9xKNSBcnZk66x',
        captured: true,
        created: 1551454924,
        currency: 'usd',
        customer: 'cus_EcSPbN4w1trfJW',
        description: "Matching 2x user2's donation",
        destination: null,
        dispute: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: null,
        livemode: false,
        metadata: {
          from: 'http://localhost:3000/user1',
          to: 'http://localhost:3000/tipbox',
          customerEmail: 'user1@opencollective.com',
          PaymentMethodId: '2',
        },
        on_behalf_of: null,
        order: null,
        outcome: {
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 43,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: null,
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/acct_18KWlTLzdXg9xKNS/ch_1E9DUuLzdXg9xKNSwDtK3zvU/rcpt_EcSPwGEbrNRjSHbX8bsIFH0SApJLja2',
        refunded: false,
        refunds: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/charges/ch_1E9DUuLzdXg9xKNSwDtK3zvU/refunds',
        },
        review: null,
        shipping: null,
        source: {
          id: 'card_1E9DUtLzdXg9xKNSFnKPR5Gq',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          customer: 'cus_EcSPbN4w1trfJW',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        source_transfer: null,
        statement_descriptor: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:05 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '2282',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_MfjBie5nJY1hJE',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .get('/v1/balance/history/txn_1E9DUvLzdXg9xKNSBcnZk66x')
    .reply(
      200,
      {
        id: 'txn_1E9DUvLzdXg9xKNSBcnZk66x',
        object: 'balance_transaction',
        amount: 10000,
        available_on: 1551744000,
        created: 1551454924,
        currency: 'usd',
        description: "Matching 2x user2's donation",
        exchange_rate: null,
        fee: 820,
        fee_details: [
          {
            amount: 500,
            application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
            currency: 'usd',
            description: 'OpenCollective application fee',
            type: 'application_fee',
          },
          {
            amount: 320,
            application: null,
            currency: 'usd',
            description: 'Stripe processing fees',
            type: 'stripe_fee',
          },
        ],
        net: 9180,
        source: 'ch_1E9DUuLzdXg9xKNSwDtK3zvU',
        sourced_transfers: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/transfers?source_transaction=ch_1E9DUuLzdXg9xKNSwDtK3zvU',
        },
        status: 'pending',
        type: 'charge',
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:06 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '944',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_GBe9ZPqN9RNAbH',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://www.gravatar.com:443', { encodedQueryParams: true })
    .get('/avatar/c31063b4d99c96a75d4f7f9dd2bb8dc7')
    .query({ default: '404' })
    .reply(404, '404 Not Found', [
      'Server',
      'nginx',
      'Date',
      'Fri, 01 Mar 2019 15:42:07 GMT',
      'Content-Type',
      'text/html; charset=utf-8',
      'Content-Length',
      '13',
      'Connection',
      'close',
      'Last-Modified',
      'Wed, 11 Jan 1984 08:00:00 GMT',
      'Link',
      '<https://www.gravatar.com/avatar/c31063b4d99c96a75d4f7f9dd2bb8dc7?default=404>; rel="canonical"',
      'Access-Control-Allow-Origin',
      '*',
      'ETag',
      '"404"',
      'X-nc',
      'HIT fra 4',
      'Cache-Control',
      'max-age=300',
      'Expires',
      'Fri, 01 Mar 2019 15:47:07 GMT',
      'Source-Age',
      '1568',
    ]);

  nock('https://www.gravatar.com:443', { encodedQueryParams: true })
    .get('/avatar/9cbcedbd240587a8a6620e3ed5118829')
    .query({ default: '404' })
    .reply(404, '404 Not Found', [
      'Server',
      'nginx',
      'Date',
      'Fri, 01 Mar 2019 15:42:07 GMT',
      'Content-Type',
      'text/html; charset=utf-8',
      'Content-Length',
      '13',
      'Connection',
      'close',
      'Last-Modified',
      'Wed, 11 Jan 1984 08:00:00 GMT',
      'Link',
      '<https://www.gravatar.com/avatar/9cbcedbd240587a8a6620e3ed5118829?default=404>; rel="canonical"',
      'Access-Control-Allow-Origin',
      '*',
      'ETag',
      '"404"',
      'X-nc',
      'HIT fra 2',
      'Cache-Control',
      'max-age=300',
      'Expires',
      'Fri, 01 Mar 2019 15:47:07 GMT',
      'Source-Age',
      '1568',
    ]);

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'card[number]=4242424242424242&card[exp_month]=12&card[exp_year]=2028&card[cvc]=222')
    .reply(
      200,
      {
        id: 'tok_1E9DUxDjPFcHOcTmoUdq29Jg',
        object: 'token',
        card: {
          id: 'card_1E9DUxDjPFcHOcTmYnvM8Hjn',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'unchecked',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: 'ftgJeBXvQSZ4HMCg',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454927,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:07 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '785',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_CS8uqIbJwobFQF',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'card[number]=4242424242424242&card[exp_month]=12&card[exp_year]=2028&card[cvc]=222')
    .reply(
      200,
      {
        id: 'tok_1E9DUxDjPFcHOcTmF0fBPnfE',
        object: 'token',
        card: {
          id: 'card_1E9DUxDjPFcHOcTmXrCu7dPM',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'unchecked',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: 'ftgJeBXvQSZ4HMCg',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454927,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:07 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '785',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_2bfBUrvSudAkyE',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DUxDjPFcHOcTmF0fBPnfE&description=https%3A%2F%2Fopencollective.com%2Fuser2&email=user2%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPFQu4fyCfBz',
        object: 'customer',
        account_balance: 0,
        created: 1551454928,
        currency: null,
        default_source: 'card_1E9DUxDjPFcHOcTmXrCu7dPM',
        delinquent: false,
        description: 'https://opencollective.com/user2',
        discount: null,
        email: 'user2@opencollective.com',
        invoice_prefix: '3A92BE3',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DUxDjPFcHOcTmXrCu7dPM',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPFQu4fyCfBz',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: 'ftgJeBXvQSZ4HMCg',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPFQu4fyCfBz/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPFQu4fyCfBz/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:08 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_U9SWHCqxjN67c0',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'customer=cus_EcSPFQu4fyCfBz')
    .reply(
      200,
      {
        id: 'tok_1E9DUzLzdXg9xKNS6PNRlEJq',
        object: 'token',
        card: {
          id: 'card_1E9DUyLzdXg9xKNS0RPu5cUT',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454929,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:09 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '780',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_64TIGeZ9e3ep71',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DUzLzdXg9xKNS6PNRlEJq&description=https%3A%2F%2Fopencollective.com%2Fuser2&email=user2%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPmk9oQ94lVL',
        object: 'customer',
        account_balance: 0,
        created: 1551454929,
        currency: null,
        default_source: 'card_1E9DUyLzdXg9xKNS0RPu5cUT',
        delinquent: false,
        description: 'https://opencollective.com/user2',
        discount: null,
        email: 'user2@opencollective.com',
        invoice_prefix: '0A1B0D7',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DUyLzdXg9xKNS0RPu5cUT',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPmk9oQ94lVL',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: '1ePEQxDFh2TKt5lo',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPmk9oQ94lVL/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPmk9oQ94lVL/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:09 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_AeMZ9dc5XE0bcJ',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/charges',
      'amount=5000&currency=USD&customer=cus_EcSPmk9oQ94lVL&description=Monthly%20donation%20to%20tipbox&application_fee=250&metadata[from]=http%3A%2F%2Flocalhost%3A3000%2Fuser2&metadata[to]=http%3A%2F%2Flocalhost%3A3000%2Ftipbox&metadata[customerEmail]=user2%40opencollective.com&metadata[PaymentMethodId]=3',
    )
    .reply(
      200,
      {
        id: 'ch_1E9DUzLzdXg9xKNSYP34K3Da',
        object: 'charge',
        amount: 5000,
        amount_refunded: 0,
        application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
        application_fee: 'fee_1E9DV0LzdXg9xKNS5Iez7A7w',
        application_fee_amount: 250,
        balance_transaction: 'txn_1E9DV0LzdXg9xKNSK1tPVLvb',
        captured: true,
        created: 1551454929,
        currency: 'usd',
        customer: 'cus_EcSPmk9oQ94lVL',
        description: 'Monthly donation to tipbox',
        destination: null,
        dispute: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: null,
        livemode: false,
        metadata: {
          from: 'http://localhost:3000/user2',
          to: 'http://localhost:3000/tipbox',
          customerEmail: 'user2@opencollective.com',
          PaymentMethodId: '3',
        },
        on_behalf_of: null,
        order: null,
        outcome: {
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 29,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: null,
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/acct_18KWlTLzdXg9xKNS/ch_1E9DUzLzdXg9xKNSYP34K3Da/rcpt_EcSPh2T7qJmrxmK5LU2uOVAyTGrXTZ6',
        refunded: false,
        refunds: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/charges/ch_1E9DUzLzdXg9xKNSYP34K3Da/refunds',
        },
        review: null,
        shipping: null,
        source: {
          id: 'card_1E9DUyLzdXg9xKNS0RPu5cUT',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          customer: 'cus_EcSPmk9oQ94lVL',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        source_transfer: null,
        statement_descriptor: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:10 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '2279',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_vRQMgL9b8e7Hdv',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .get('/v1/balance/history/txn_1E9DV0LzdXg9xKNSK1tPVLvb')
    .reply(
      200,
      {
        id: 'txn_1E9DV0LzdXg9xKNSK1tPVLvb',
        object: 'balance_transaction',
        amount: 5000,
        available_on: 1551744000,
        created: 1551454929,
        currency: 'usd',
        description: 'Monthly donation to tipbox',
        exchange_rate: null,
        fee: 425,
        fee_details: [
          {
            amount: 250,
            application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
            currency: 'usd',
            description: 'OpenCollective application fee',
            type: 'application_fee',
          },
          {
            amount: 175,
            application: null,
            currency: 'usd',
            description: 'Stripe processing fees',
            type: 'stripe_fee',
          },
        ],
        net: 4575,
        source: 'ch_1E9DUzLzdXg9xKNSYP34K3Da',
        sourced_transfers: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/transfers?source_transaction=ch_1E9DUzLzdXg9xKNSYP34K3Da',
        },
        status: 'pending',
        type: 'charge',
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:10 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '941',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_JzQjn5bPPCq2MH',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DUxDjPFcHOcTmoUdq29Jg&description=https%3A%2F%2Fopencollective.com%2Fuser1&email=user1%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPKeGPmGLpTE',
        object: 'customer',
        account_balance: 0,
        created: 1551454931,
        currency: null,
        default_source: 'card_1E9DUxDjPFcHOcTmYnvM8Hjn',
        delinquent: false,
        description: 'https://opencollective.com/user1',
        discount: null,
        email: 'user1@opencollective.com',
        invoice_prefix: '3FEC3D7',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DUxDjPFcHOcTmYnvM8Hjn',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPKeGPmGLpTE',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: 'ftgJeBXvQSZ4HMCg',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPKeGPmGLpTE/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPKeGPmGLpTE/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:11 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_U8zDd5toKGY8m8',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'customer=cus_EcSPKeGPmGLpTE')
    .reply(
      200,
      {
        id: 'tok_1E9DV1LzdXg9xKNSmD510Hbe',
        object: 'token',
        card: {
          id: 'card_1E9DV1LzdXg9xKNSWCyNi7JW',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454931,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:11 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '780',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_hxueiy6zUECpiV',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/customers',
      'source=tok_1E9DV1LzdXg9xKNSmD510Hbe&description=https%3A%2F%2Fopencollective.com%2Fuser1&email=user1%40opencollective.com',
    )
    .reply(
      200,
      {
        id: 'cus_EcSPCQqP4SRLJx',
        object: 'customer',
        account_balance: 0,
        created: 1551454932,
        currency: null,
        default_source: 'card_1E9DV1LzdXg9xKNSWCyNi7JW',
        delinquent: false,
        description: 'https://opencollective.com/user1',
        discount: null,
        email: 'user1@opencollective.com',
        invoice_prefix: '1D44AC3',
        invoice_settings: { custom_fields: null, footer: null },
        livemode: false,
        metadata: {},
        shipping: null,
        sources: {
          object: 'list',
          data: [
            {
              id: 'card_1E9DV1LzdXg9xKNSWCyNi7JW',
              object: 'card',
              address_city: null,
              address_country: null,
              address_line1: null,
              address_line1_check: null,
              address_line2: null,
              address_state: null,
              address_zip: null,
              address_zip_check: null,
              brand: 'Visa',
              country: 'US',
              customer: 'cus_EcSPCQqP4SRLJx',
              cvc_check: 'pass',
              dynamic_last4: null,
              exp_month: 12,
              exp_year: 2028,
              fingerprint: '1ePEQxDFh2TKt5lo',
              funding: 'credit',
              last4: '4242',
              metadata: {},
              name: null,
              tokenization_method: null,
            },
          ],
          has_more: false,
          total_count: 1,
          url: '/v1/customers/cus_EcSPCQqP4SRLJx/sources',
        },
        subscriptions: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/customers/cus_EcSPCQqP4SRLJx/subscriptions',
        },
        tax_info: null,
        tax_info_verification: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:12 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '1609',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_gIlnVbUiDpIz1F',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post(
      '/v1/charges',
      'amount=10000&currency=USD&customer=cus_EcSPCQqP4SRLJx&description=Matching%202x%20user2%27s%20donation&application_fee=500&metadata[from]=http%3A%2F%2Flocalhost%3A3000%2Fuser1&metadata[to]=http%3A%2F%2Flocalhost%3A3000%2Ftipbox&metadata[customerEmail]=user1%40opencollective.com&metadata[PaymentMethodId]=2',
    )
    .reply(
      200,
      {
        id: 'ch_1E9DV2LzdXg9xKNSuaBCY5gs',
        object: 'charge',
        amount: 10000,
        amount_refunded: 0,
        application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
        application_fee: 'fee_1E9DV2LzdXg9xKNSK1XvaxMC',
        application_fee_amount: 500,
        balance_transaction: 'txn_1E9DV3LzdXg9xKNSdASDiKeA',
        captured: true,
        created: 1551454932,
        currency: 'usd',
        customer: 'cus_EcSPCQqP4SRLJx',
        description: "Matching 2x user2's donation",
        destination: null,
        dispute: null,
        failure_code: null,
        failure_message: null,
        fraud_details: {},
        invoice: null,
        livemode: false,
        metadata: {
          from: 'http://localhost:3000/user1',
          to: 'http://localhost:3000/tipbox',
          customerEmail: 'user1@opencollective.com',
          PaymentMethodId: '2',
        },
        on_behalf_of: null,
        order: null,
        outcome: {
          network_status: 'approved_by_network',
          reason: null,
          risk_level: 'normal',
          risk_score: 19,
          seller_message: 'Payment complete.',
          type: 'authorized',
        },
        paid: true,
        payment_intent: null,
        receipt_email: null,
        receipt_number: null,
        receipt_url:
          'https://pay.stripe.com/receipts/acct_18KWlTLzdXg9xKNS/ch_1E9DV2LzdXg9xKNSuaBCY5gs/rcpt_EcSP8Fv5hYMLgJEAD423p8810BUi22I',
        refunded: false,
        refunds: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/charges/ch_1E9DV2LzdXg9xKNSuaBCY5gs/refunds',
        },
        review: null,
        shipping: null,
        source: {
          id: 'card_1E9DV1LzdXg9xKNSWCyNi7JW',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          customer: 'cus_EcSPCQqP4SRLJx',
          cvc_check: 'pass',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: '1ePEQxDFh2TKt5lo',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        source_transfer: null,
        statement_descriptor: null,
        status: 'succeeded',
        transfer_data: null,
        transfer_group: null,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:13 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '2282',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_SfG6kqTWT8VyYG',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .get('/v1/balance/history/txn_1E9DV3LzdXg9xKNSdASDiKeA')
    .reply(
      200,
      {
        id: 'txn_1E9DV3LzdXg9xKNSdASDiKeA',
        object: 'balance_transaction',
        amount: 10000,
        available_on: 1551744000,
        created: 1551454932,
        currency: 'usd',
        description: "Matching 2x user2's donation",
        exchange_rate: null,
        fee: 820,
        fee_details: [
          {
            amount: 320,
            application: null,
            currency: 'usd',
            description: 'Stripe processing fees',
            type: 'stripe_fee',
          },
          {
            amount: 500,
            application: 'ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue',
            currency: 'usd',
            description: 'OpenCollective application fee',
            type: 'application_fee',
          },
        ],
        net: 9180,
        source: 'ch_1E9DV2LzdXg9xKNSuaBCY5gs',
        sourced_transfers: {
          object: 'list',
          data: [],
          has_more: false,
          total_count: 0,
          url: '/v1/transfers?source_transaction=ch_1E9DV2LzdXg9xKNSuaBCY5gs',
        },
        status: 'pending',
        type: 'charge',
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:13 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '944',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_3JyyHEb6Lqi6hv',
        'Stripe-Account',
        'acct_18KWlTLzdXg9xKNS',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://www.gravatar.com:443', { encodedQueryParams: true })
    .get('/avatar/c31063b4d99c96a75d4f7f9dd2bb8dc7')
    .query({ default: '404' })
    .reply(404, '404 Not Found', [
      'Server',
      'nginx',
      'Date',
      'Fri, 01 Mar 2019 15:42:15 GMT',
      'Content-Type',
      'text/html; charset=utf-8',
      'Content-Length',
      '13',
      'Connection',
      'close',
      'Last-Modified',
      'Wed, 11 Jan 1984 08:00:00 GMT',
      'Link',
      '<https://www.gravatar.com/avatar/c31063b4d99c96a75d4f7f9dd2bb8dc7?default=404>; rel="canonical"',
      'Access-Control-Allow-Origin',
      '*',
      'ETag',
      '"404"',
      'X-nc',
      'HIT fra 4',
      'Cache-Control',
      'max-age=300',
      'Expires',
      'Fri, 01 Mar 2019 15:47:15 GMT',
      'Source-Age',
      '1576',
    ]);

  nock('https://www.gravatar.com:443', { encodedQueryParams: true })
    .get('/avatar/9cbcedbd240587a8a6620e3ed5118829')
    .query({ default: '404' })
    .reply(404, '404 Not Found', [
      'Server',
      'nginx',
      'Date',
      'Fri, 01 Mar 2019 15:42:15 GMT',
      'Content-Type',
      'text/html; charset=utf-8',
      'Content-Length',
      '13',
      'Connection',
      'close',
      'Last-Modified',
      'Wed, 11 Jan 1984 08:00:00 GMT',
      'Link',
      '<https://www.gravatar.com/avatar/9cbcedbd240587a8a6620e3ed5118829?default=404>; rel="canonical"',
      'Access-Control-Allow-Origin',
      '*',
      'ETag',
      '"404"',
      'X-nc',
      'HIT fra 2',
      'Cache-Control',
      'max-age=300',
      'Expires',
      'Fri, 01 Mar 2019 15:47:15 GMT',
      'Source-Age',
      '1576',
    ]);

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'card[number]=4242424242424242&card[exp_month]=12&card[exp_year]=2028&card[cvc]=222')
    .reply(
      200,
      {
        id: 'tok_1E9DV5DjPFcHOcTmdm0KoV9G',
        object: 'token',
        card: {
          id: 'card_1E9DV5DjPFcHOcTm6Wu4cpdf',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'unchecked',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: 'ftgJeBXvQSZ4HMCg',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454935,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:15 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '785',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_B6uGHEI7XEgius',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );

  nock('https://api.stripe.com:443', { encodedQueryParams: true })
    .post('/v1/tokens', 'card[number]=4242424242424242&card[exp_month]=12&card[exp_year]=2028&card[cvc]=222')
    .reply(
      200,
      {
        id: 'tok_1E9DV5DjPFcHOcTmQMaEDENZ',
        object: 'token',
        card: {
          id: 'card_1E9DV5DjPFcHOcTmDI5ENvY2',
          object: 'card',
          address_city: null,
          address_country: null,
          address_line1: null,
          address_line1_check: null,
          address_line2: null,
          address_state: null,
          address_zip: null,
          address_zip_check: null,
          brand: 'Visa',
          country: 'US',
          cvc_check: 'unchecked',
          dynamic_last4: null,
          exp_month: 12,
          exp_year: 2028,
          fingerprint: 'ftgJeBXvQSZ4HMCg',
          funding: 'credit',
          last4: '4242',
          metadata: {},
          name: null,
          tokenization_method: null,
        },
        client_ip: '91.65.137.48',
        created: 1551454935,
        livemode: false,
        type: 'card',
        used: false,
      },
      [
        'Server',
        'nginx',
        'Date',
        'Fri, 01 Mar 2019 15:42:15 GMT',
        'Content-Type',
        'application/json',
        'Content-Length',
        '785',
        'Connection',
        'keep-alive',
        'Access-Control-Allow-Credentials',
        'true',
        'Access-Control-Allow-Methods',
        'GET, POST, HEAD, OPTIONS, DELETE',
        'Access-Control-Allow-Origin',
        '*',
        'Access-Control-Expose-Headers',
        'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
        'Access-Control-Max-Age',
        '300',
        'Cache-Control',
        'no-cache, no-store',
        'Request-Id',
        'req_kQelXXymsAYzkI',
        'Stripe-Version',
        '2015-04-07',
        'Strict-Transport-Security',
        'max-age=31556926; includeSubDomains; preload',
      ],
    );
}
