import nock from 'nock';

export default function() {

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "card%5Bnumber%5D=4242424242424242&card%5Bexp_month%5D=12&card%5Bexp_year%5D=2028&card%5Bcvc%5D=222")
  .reply(200, {"id":"tok_1B6BjpDjPFcHOcTmCz4SGEw8","object":"token","card":{"id":"card_1B6BjpDjPFcHOcTmLSOFrquW","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"unchecked","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404169,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6BjpDjPFcHOcTmCz4SGEw8&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT7zk3PBApsShc","object":"customer","account_balance":0,"created":1506404170,"currency":null,"default_source":"card_1B6BjpDjPFcHOcTmLSOFrquW","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6BjpDjPFcHOcTmLSOFrquW","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT7zk3PBApsShc","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT7zk3PBApsShc/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT7zk3PBApsShc/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "customer=cus_BT7zk3PBApsShc")
  .reply(200, {"id":"tok_1B6BjrD8MNtzsDcg7gHCHRcr","object":"token","card":{"id":"card_1B6BjrD8MNtzsDcgOSro4sRp","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404171,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6BjrD8MNtzsDcg7gHCHRcr&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT7zbQJt3S0ZDd","object":"customer","account_balance":0,"created":1506404171,"currency":null,"default_source":"card_1B6BjrD8MNtzsDcgOSro4sRp","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6BjrD8MNtzsDcgOSro4sRp","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT7zbQJt3S0ZDd","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT7zbQJt3S0ZDd/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT7zbQJt3S0ZDd/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/charges', /amount=35000&currency=USD&customer=cus_BT7zbQJt3S0ZDd&description=&application_fee=1750&metadata%5Bfrom%5D=http%3A%2F%2Flocalhost%3A3000%2Fphilmod&metadata%5Bto%5D=http%3A%2F%2Flocalhost%3A3000%2Fscouts&metadata%5BcustomerEmail%5D=user1%40opencollective.com&metadata%5BPaymentMethodId%5D=[0-9]+/)
  .reply(200, {"id":"ch_1B6BjsD8MNtzsDcgcYMNu7CV","object":"charge","amount":35000,"amount_refunded":0,"application":"ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue","application_fee":"fee_1B6BjsD8MNtzsDcgMQnVkyT5","balance_transaction":"txn_1B6BjsD8MNtzsDcgPLwta4mQ","captured":true,"created":1506404172,"currency":"usd","customer":"cus_BT7zbQJt3S0ZDd","description":"","destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":false,"metadata":{"from":"http://localhost:3000/philmod","to":"http://localhost:3000/scouts","customerEmail":"user1@opencollective.com","PaymentMethodId":"4"},"on_behalf_of":null,"order":null,"outcome":{"network_status":"approved_by_network","reason":null,"risk_level":"normal","seller_message":"Payment complete.","type":"authorized"},"paid":true,"receipt_email":null,"receipt_number":null,"refunded":false,"refunds":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/charges/ch_1B6BjsD8MNtzsDcgcYMNu7CV/refunds"},"review":null,"shipping":null,"source":{"id":"card_1B6BjrD8MNtzsDcgOSro4sRp","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT7zbQJt3S0ZDd","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"source_transfer":null,"statement_descriptor":null,"status":"succeeded","transfer_group":null});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .get('/v1/plans/USD-MONTH-35000')
  .reply(200, {"id":"USD-MONTH-35000","object":"plan","amount":35000,"created":1504702187,"currency":"usd","interval":"month","interval_count":1,"livemode":false,"metadata":{},"name":"USD-MONTH-35000","statement_descriptor":null,"trial_period_days":null});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "card%5Bnumber%5D=4242424242424242&card%5Bexp_month%5D=12&card%5Bexp_year%5D=2028&card%5Bcvc%5D=222")
  .reply(200, {"id":"tok_1B6BjwDjPFcHOcTmgDhmLgIw","object":"token","card":{"id":"card_1B6BjwDjPFcHOcTmnT5Ehk4v","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"unchecked","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404176,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6BjwDjPFcHOcTmgDhmLgIw&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT7z2BhyY75lZH","object":"customer","account_balance":0,"created":1506404176,"currency":null,"default_source":"card_1B6BjwDjPFcHOcTmnT5Ehk4v","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6BjwDjPFcHOcTmnT5Ehk4v","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT7z2BhyY75lZH","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT7z2BhyY75lZH/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT7z2BhyY75lZH/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "customer=cus_BT7z2BhyY75lZH")
  .reply(200, {"id":"tok_1B6BjxD8MNtzsDcgAkd6gycv","object":"token","card":{"id":"card_1B6BjxD8MNtzsDcgdZCeyiGZ","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404177,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6BjxD8MNtzsDcgAkd6gycv&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT7zd4PqcEwJ2u","object":"customer","account_balance":0,"created":1506404178,"currency":null,"default_source":"card_1B6BjxD8MNtzsDcgdZCeyiGZ","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6BjxD8MNtzsDcgdZCeyiGZ","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT7zd4PqcEwJ2u","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT7zd4PqcEwJ2u/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT7zd4PqcEwJ2u/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/charges', /amount=35000&currency=USD&customer=cus_BT7zd4PqcEwJ2u&description=&application_fee=1750&metadata%5Bfrom%5D=http%3A%2F%2Flocalhost%3A3000%2Fphilmod&metadata%5Bto%5D=http%3A%2F%2Flocalhost%3A3000%2Fscouts&metadata%5BcustomerEmail%5D=user1%40opencollective.com&metadata%5BPaymentMethodId%5D=[0-9]+/)
  .reply(200, {"id":"ch_1B6BjyD8MNtzsDcgEjzY51t7","object":"charge","amount":35000,"amount_refunded":0,"application":"ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue","application_fee":"fee_1B6BjzD8MNtzsDcgEE5Q0oIV","balance_transaction":"txn_1B6BjzD8MNtzsDcgM7ZGz4Qi","captured":true,"created":1506404178,"currency":"usd","customer":"cus_BT7zd4PqcEwJ2u","description":"","destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":false,"metadata":{"from":"http://localhost:3000/philmod","to":"http://localhost:3000/scouts","customerEmail":"user1@opencollective.com","PaymentMethodId":"4"},"on_behalf_of":null,"order":null,"outcome":{"network_status":"approved_by_network","reason":null,"risk_level":"normal","seller_message":"Payment complete.","type":"authorized"},"paid":true,"receipt_email":null,"receipt_number":null,"refunded":false,"refunds":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/charges/ch_1B6BjyD8MNtzsDcgEjzY51t7/refunds"},"review":null,"shipping":null,"source":{"id":"card_1B6BjxD8MNtzsDcgdZCeyiGZ","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT7zd4PqcEwJ2u","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"source_transfer":null,"statement_descriptor":null,"status":"succeeded","transfer_group":null});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .get('/v1/plans/USD-MONTH-35000')
  .reply(200, {"id":"USD-MONTH-35000","object":"plan","amount":35000,"created":1504702187,"currency":"usd","interval":"month","interval_count":1,"livemode":false,"metadata":{},"name":"USD-MONTH-35000","statement_descriptor":null,"trial_period_days":null});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "card%5Bnumber%5D=4242424242424242&card%5Bexp_month%5D=12&card%5Bexp_year%5D=2028&card%5Bcvc%5D=222")
  .reply(200, {"id":"tok_1B6Bk2DjPFcHOcTmhAXubWSZ","object":"token","card":{"id":"card_1B6Bk2DjPFcHOcTmrBsuDdZS","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"unchecked","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404182,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6Bk2DjPFcHOcTmhAXubWSZ&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT80S96oEdduIM","object":"customer","account_balance":0,"created":1506404183,"currency":null,"default_source":"card_1B6Bk2DjPFcHOcTmrBsuDdZS","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6Bk2DjPFcHOcTmrBsuDdZS","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT80S96oEdduIM","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT80S96oEdduIM/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT80S96oEdduIM/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "customer=cus_BT80S96oEdduIM")
  .reply(200, {"id":"tok_1B6Bk4D8MNtzsDcgit3wd0AO","object":"token","card":{"id":"card_1B6Bk4D8MNtzsDcgTUcAYpMK","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404184,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6Bk4D8MNtzsDcgit3wd0AO&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT80Bv5uUXF6Ov","object":"customer","account_balance":0,"created":1506404184,"currency":null,"default_source":"card_1B6Bk4D8MNtzsDcgTUcAYpMK","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6Bk4D8MNtzsDcgTUcAYpMK","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT80Bv5uUXF6Ov","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT80Bv5uUXF6Ov/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT80Bv5uUXF6Ov/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/charges', /amount=35000&currency=USD&customer=cus_BT80Bv5uUXF6Ov&description=&application_fee=1750&metadata%5Bfrom%5D=http%3A%2F%2Flocalhost%3A3000%2Fphilmod&metadata%5Bto%5D=http%3A%2F%2Flocalhost%3A3000%2Fscouts&metadata%5BcustomerEmail%5D=user1%40opencollective.com&metadata%5BPaymentMethodId%5D=[0-9]+/)
  .reply(200, {"id":"ch_1B6Bk5D8MNtzsDcgZuk6GsZP","object":"charge","amount":35000,"amount_refunded":0,"application":"ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue","application_fee":"fee_1B6Bk5D8MNtzsDcgjDeaIxhR","balance_transaction":"txn_1B6Bk5D8MNtzsDcgCJI1FS4F","captured":true,"created":1506404185,"currency":"usd","customer":"cus_BT80Bv5uUXF6Ov","description":"","destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":false,"metadata":{"from":"http://localhost:3000/philmod","to":"http://localhost:3000/scouts","customerEmail":"user1@opencollective.com","PaymentMethodId":"4"},"on_behalf_of":null,"order":null,"outcome":{"network_status":"approved_by_network","reason":null,"risk_level":"normal","seller_message":"Payment complete.","type":"authorized"},"paid":true,"receipt_email":null,"receipt_number":null,"refunded":false,"refunds":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/charges/ch_1B6Bk5D8MNtzsDcgZuk6GsZP/refunds"},"review":null,"shipping":null,"source":{"id":"card_1B6Bk4D8MNtzsDcgTUcAYpMK","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT80Bv5uUXF6Ov","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"source_transfer":null,"statement_descriptor":null,"status":"succeeded","transfer_group":null});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .get('/v1/plans/USD-MONTH-35000')
  .reply(200, {"id":"USD-MONTH-35000","object":"plan","amount":35000,"created":1504702187,"currency":"usd","interval":"month","interval_count":1,"livemode":false,"metadata":{},"name":"USD-MONTH-35000","statement_descriptor":null,"trial_period_days":null});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "card%5Bnumber%5D=4242424242424242&card%5Bexp_month%5D=12&card%5Bexp_year%5D=2028&card%5Bcvc%5D=222")
  .reply(200, {"id":"tok_1B6Bk9DjPFcHOcTm6byFgPus","object":"token","card":{"id":"card_1B6Bk9DjPFcHOcTmybIPIQTE","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"unchecked","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404189,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6Bk9DjPFcHOcTm6byFgPus&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT80ICRN6Hwurp","object":"customer","account_balance":0,"created":1506404190,"currency":null,"default_source":"card_1B6Bk9DjPFcHOcTmybIPIQTE","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6Bk9DjPFcHOcTmybIPIQTE","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT80ICRN6Hwurp","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"ftgJeBXvQSZ4HMCg","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT80ICRN6Hwurp/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT80ICRN6Hwurp/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/tokens', "customer=cus_BT80ICRN6Hwurp")
  .reply(200, {"id":"tok_1B6BkBD8MNtzsDcgS1DAdSvK","object":"token","card":{"id":"card_1B6BkBD8MNtzsDcgeqgdwOKS","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"client_ip":"38.88.150.114","created":1506404191,"livemode":false,"type":"card","used":false});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/customers', "source=tok_1B6BkBD8MNtzsDcgS1DAdSvK&description=https%3A%2F%2Fopencollective.com%2Fphilmod&email=user1%40opencollective.com")
  .reply(200, {"id":"cus_BT80BX3VSPHlpD","object":"customer","account_balance":0,"created":1506404191,"currency":null,"default_source":"card_1B6BkBD8MNtzsDcgeqgdwOKS","delinquent":false,"description":"https://opencollective.com/philmod","discount":null,"email":"user1@opencollective.com","livemode":false,"metadata":{},"shipping":null,"sources":{"object":"list","data":[{"id":"card_1B6BkBD8MNtzsDcgeqgdwOKS","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT80BX3VSPHlpD","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null}],"has_more":false,"total_count":1,"url":"/v1/customers/cus_BT80BX3VSPHlpD/sources"},"subscriptions":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/customers/cus_BT80BX3VSPHlpD/subscriptions"}});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .post('/v1/charges', /amount=35000&currency=USD&customer=cus_BT80BX3VSPHlpD&description=&application_fee=1750&metadata%5Bfrom%5D=http%3A%2F%2Flocalhost%3A3000%2Fphilmod&metadata%5Bto%5D=http%3A%2F%2Flocalhost%3A3000%2Fscouts&metadata%5BcustomerEmail%5D=user1%40opencollective.com&metadata%5BPaymentMethodId%5D=[0-9]+/)
  .reply(200, {"id":"ch_1B6BkCD8MNtzsDcgovTSFGEQ","object":"charge","amount":35000,"amount_refunded":0,"application":"ca_68FQcZXEcV66Kjg7egLnR1Ce87cqwoue","application_fee":"fee_1B6BkCD8MNtzsDcgBASsVu7V","balance_transaction":"txn_1B6BkCD8MNtzsDcggyyd7f6t","captured":true,"created":1506404192,"currency":"usd","customer":"cus_BT80BX3VSPHlpD","description":"","destination":null,"dispute":null,"failure_code":null,"failure_message":null,"fraud_details":{},"invoice":null,"livemode":false,"metadata":{"from":"http://localhost:3000/philmod","to":"http://localhost:3000/scouts","customerEmail":"user1@opencollective.com","PaymentMethodId":"4"},"on_behalf_of":null,"order":null,"outcome":{"network_status":"approved_by_network","reason":null,"risk_level":"normal","seller_message":"Payment complete.","type":"authorized"},"paid":true,"receipt_email":null,"receipt_number":null,"refunded":false,"refunds":{"object":"list","data":[],"has_more":false,"total_count":0,"url":"/v1/charges/ch_1B6BkCD8MNtzsDcgovTSFGEQ/refunds"},"review":null,"shipping":null,"source":{"id":"card_1B6BkBD8MNtzsDcgeqgdwOKS","object":"card","address_city":null,"address_country":null,"address_line1":null,"address_line1_check":null,"address_line2":null,"address_state":null,"address_zip":null,"address_zip_check":null,"brand":"Visa","country":"US","customer":"cus_BT80BX3VSPHlpD","cvc_check":"pass","dynamic_last4":null,"exp_month":12,"exp_year":2028,"fingerprint":"nt4eriIIhN3fiPZF","funding":"credit","last4":"4242","metadata":{},"name":null,"tokenization_method":null},"source_transfer":null,"statement_descriptor":null,"status":"succeeded","transfer_group":null});

nock('https://api.stripe.com:443', {"encodedQueryParams":true})
  .get('/v1/plans/USD-MONTH-35000')
  .reply(200, {"id":"USD-MONTH-35000","object":"plan","amount":35000,"created":1504702187,"currency":"usd","interval":"month","interval_count":1,"livemode":false,"metadata":{},"name":"USD-MONTH-35000","statement_descriptor":null,"trial_period_days":null});

}