export default {
  COLLECTIVE_CREATED: 'COLLECTIVE_CREATED',
  COLLECTIVE_APPLY: 'COLLECTIVE_APPLY',
  COLLECTIVE_APPROVED: 'COLLECTIVE_APPROVED',
  COLLECTIVE_COMMENT_CREATED: 'COLLECTIVE_COMMENT_CREATED',
  COLLECTIVE_EXPENSE_CREATED: 'COLLECTIVE_EXPENSE_CREATED',
  COLLECTIVE_EXPENSE_DELETED: 'COLLECTIVE_EXPENSE_DELETED',
  COLLECTIVE_MEMBER_CREATED: 'COLLECTIVE_MEMBER_CREATED',
  COLLECTIVE_TRANSACTION_CREATED: 'COLLECTIVE_TRANSACTION_CREATED',
  COLLECTIVE_UPDATE_CREATED: 'COLLECTIVE_UPDATE_CREATED',
  CONNECTED_ACCOUNT_CREATED: 'CONNECTED_ACCOUNT_CREATED',
  SUBSCRIPTION_CANCELED: 'SUBSCRIPTION_CANCELED',
  TICKET_CONFIRMED: 'TICKET_CONFIRMED',
};
