export const ActivityClasses = {
  COLLECTIVE: 'collectives',
  EXPENSES: 'expenses',
  CONTRIBUTIONS: 'contributions',
  ACTIVITIES_UPDATES: 'activitiesUpdates',
  VIRTUAL_CARDS: 'virtualCards',
  FUND_EVENTS: 'fundsEvents',
  REPORTS: 'reports',
} as const;

export const ActivityTypes = {
  ACTIVATED_COLLECTIVE_AS_HOST: 'activated.collective.as.host',
  ACTIVATED_COLLECTIVE_AS_INDEPENDENT: 'activated.collective.as.independent',
  ACTIVITY_ALL: 'all',
  BACKYOURSTACK_DISPATCH_CONFIRMED: 'backyourstack.dispatch.confirmed',
  COLLECTIVE_APPLY: 'collective.apply',
  COLLECTIVE_APPROVED: 'collective.approved',
  COLLECTIVE_COMMENT_CREATED: 'collective.comment.created',
  COLLECTIVE_CONTACT: 'collective.contact',
  COLLECTIVE_CONVERSATION_CREATED: 'collective.conversation.created',
  COLLECTIVE_CORE_MEMBER_ADDED: 'collective.core.member.added',
  COLLECTIVE_CORE_MEMBER_EDITED: 'collective.core.member.edited',
  COLLECTIVE_CORE_MEMBER_INVITATION_DECLINED: 'collective.core.member.invitation.declined',
  COLLECTIVE_CORE_MEMBER_INVITED: 'collective.core.member.invited',
  COLLECTIVE_CORE_MEMBER_REMOVED: 'collective.core.member.removed',
  COLLECTIVE_CREATED_GITHUB: 'collective.created.github',
  COLLECTIVE_CREATED: 'collective.created',
  COLLECTIVE_EDITED: 'collective.edited',
  COLLECTIVE_EXPENSE_APPROVED: 'collective.expense.approved',
  COLLECTIVE_EXPENSE_CREATED: 'collective.expense.created',
  COLLECTIVE_EXPENSE_DELETED: 'collective.expense.deleted',
  COLLECTIVE_EXPENSE_ERROR: 'collective.expense.error',
  COLLECTIVE_EXPENSE_INVITE_DRAFTED: 'collective.expense.invite.drafted',
  COLLECTIVE_EXPENSE_MARKED_AS_INCOMPLETE: 'collective.expense.incomplete',
  COLLECTIVE_EXPENSE_MARKED_AS_SPAM: 'collective.expense.spam',
  COLLECTIVE_EXPENSE_MARKED_AS_UNPAID: 'collective.expense.unpaid',
  COLLECTIVE_EXPENSE_MISSING_RECEIPT: 'collective.expense.missing.receipt',
  COLLECTIVE_EXPENSE_MOVED: 'collective.expense.moved',
  COLLECTIVE_EXPENSE_PAID: 'collective.expense.paid',
  COLLECTIVE_EXPENSE_PROCESSING: 'collective.expense.processing',
  COLLECTIVE_EXPENSE_PUT_ON_HOLD: 'collective.expense.putOnHold',
  COLLECTIVE_EXPENSE_RECURRING_DRAFTED: 'collective.expense.recurring.drafted',
  COLLECTIVE_EXPENSE_REJECTED: 'collective.expense.rejected',
  COLLECTIVE_EXPENSE_RELEASED_FROM_HOLD: 'collective.expense.releasedFromHold',
  COLLECTIVE_EXPENSE_SCHEDULED_FOR_PAYMENT: 'collective.expense.scheduledForPayment',
  COLLECTIVE_EXPENSE_UNAPPROVED: 'collective.expense.unapproved',
  COLLECTIVE_EXPENSE_UPDATED: 'collective.expense.updated',
  COLLECTIVE_FROZEN: 'collective.frozen',
  COLLECTIVE_MEMBER_CREATED: 'collective.member.created',
  COLLECTIVE_MEMBER_INVITED: 'collective.member.invited',
  COLLECTIVE_MONTHLY_REPORT: 'collective.monthlyreport',
  COLLECTIVE_REJECTED: 'collective.rejected',
  COLLECTIVE_TRANSACTION_CREATED: 'collective.transaction.created',
  COLLECTIVE_UNFROZEN: 'collective.unfrozen',
  COLLECTIVE_UNHOSTED: 'collective.unhosted',
  COLLECTIVE_UPDATE_CREATED: 'collective.update.created',
  COLLECTIVE_UPDATE_PUBLISHED: 'collective.update.published',
  COLLECTIVE_VIRTUAL_CARD_ADDED: 'collective.virtualcard.added',
  COLLECTIVE_VIRTUAL_CARD_MISSING_RECEIPTS: 'collective.virtualcard.missing.receipts',
  COLLECTIVE_VIRTUAL_CARD_SUSPENDED: 'collective.virtualcard.suspended',
  CONNECTED_ACCOUNT_CREATED: 'connected_account.created',
  CONTRIBUTION_REJECTED: 'contribution.rejected',
  CONVERSATION_COMMENT_CREATED: 'conversation.comment.created',
  DEACTIVATED_COLLECTIVE_AS_HOST: 'deactivated.collective.as.host',
  EXPENSE_COMMENT_CREATED: 'expense.comment.created',
  ORDER_CANCELED_ARCHIVED_COLLECTIVE: 'order.canceled.archived.collective',
  ORDER_PENDING_CONTRIBUTION_NEW: 'order.new.pendingFinancialContribution',
  ORDER_PENDING_CONTRIBUTION_REMINDER: 'order.reminder.pendingFinancialContribution',
  ORDER_PROCESSING_CRYPTO: 'order.processing.crypto',
  ORDER_PROCESSING: 'order.processing',
  ORDER_THANKYOU: 'order.thankyou',
  ORDERS_SUSPICIOUS: 'orders.suspicious',
  ORGANIZATION_COLLECTIVE_CREATED: 'organization.collective.created',
  PAYMENT_CREDITCARD_CONFIRMATION: 'payment.creditcard.confirmation',
  PAYMENT_CREDITCARD_EXPIRING: 'payment.creditcard.expiring',
  PAYMENT_FAILED: 'payment.failed',
  SUBSCRIPTION_ACTIVATED: 'subscription.activated',
  SUBSCRIPTION_CANCELED: 'subscription.canceled',
  SUBSCRIPTION_CONFIRMED: 'subscription.confirmed',
  TAXFORM_REQUEST: 'taxform.request',
  TICKET_CONFIRMED: 'ticket.confirmed',
  UPDATE_COMMENT_CREATED: 'update.comment.created',
  USER_CARD_CLAIMED: 'user.card.claimed',
  USER_CARD_INVITED: 'user.card.invited',
  USER_CHANGE_EMAIL: 'user.changeEmail',
  USER_CREATED: 'user.created',
  USER_NEW_TOKEN: 'user.new.token',
  USER_PAYMENT_METHOD_CREATED: 'user.paymentMethod.created',
  USER_SIGNIN: 'user.signin',
  VIRTUAL_CARD_CHARGE_DECLINED: 'virtualcard.charge.declined',
  VIRTUAL_CARD_PURCHASE: 'virtualcard.purchase',
  VIRTUAL_CARD_REQUESTED: 'virtual_card.requested',
  WEBHOOK_PAYPAL_RECEIVED: 'webhook.paypal.received',
  WEBHOOK_STRIPE_RECEIVED: 'webhook.stripe.received',
} as const;

export const ActivityAttribution = {
  // Activities initiated by this account
  AUTHORED: 'AUTHORED',
  // Activities that targeted this account
  RECEIVED: 'RECEIVED',
  // Activities where author and target both points to this account (e.g. settings update)
  SELF: 'SELF',
  // Activities that happened on accounts hosted by this account
  HOSTED_ACCOUNTS: 'HOSTED_ACCOUNTS',
} as const;
