/** Defines contributions types */
export const ContributionTypes = {
  FINANCIAL_CUSTOM: 'FINANCIAL_CUSTOM',
  FINANCIAL_ONE_TIME: 'FINANCIAL_ONE_TIME',
  FINANCIAL_RECURRING: 'FINANCIAL_RECURRING',
  FINANCIAL_GOAL: 'FINANCIAL_GOAL',
  PRODUCT: 'PRODUCT',
  TICKET: 'TICKET',
  MEMBERSHIP: 'MEMBERSHIP',
  EVENT_PARTICIPATE: 'EVENT_PARTICIPATE',
  EVENT_PASSED: 'EVENT_PASSED',
};

export default ContributionTypes;
