/** Defines contributions types */
export const ContributionTypes = {
  FINANCIAL_CUSTOM: 'FINANCIAL_CUSTOM',
  FINANCIAL_CRYPTO: 'FINANCIAL_CRYPTO',
  FINANCIAL_ONE_TIME: 'FINANCIAL_ONE_TIME',
  FINANCIAL_RECURRING: 'FINANCIAL_RECURRING',
  FINANCIAL_GOAL: 'FINANCIAL_GOAL',
  PRODUCT: 'PRODUCT',
  TICKET: 'TICKET',
  MEMBERSHIP: 'MEMBERSHIP',
  EVENT_PARTICIPATE: 'EVENT_PARTICIPATE',
  EVENT_PASSED: 'EVENT_PASSED',
  TIER_PASSED: 'TIER_PASSED',
  CHILD_COLLECTIVE: 'CHILD_COLLECTIVE',
  PROJECT: 'PROJECT',
  ARCHIVED_PROJECT: 'ARCHIVED_PROJECT',
};
