export const DISMISSABLE_HELP_MESSAGE_KEY = 'dismissedHelpMessages';

/** Defines IDs for dismissible help messages */
export const HELP_MESSAGE = {
  EXPENSE_CREATE_INFO: 'EXPENSE_CREATE_INFO',
  WELCOME_TO_DASHBOARD: 'WELCOME_TO_DASHBOARD',
  POTENTIAL_VENDORS: 'POTENTIAL_VENDORS',
  COLLECTIVE_OVERVIEW_WELCOME: 'COLLECTIVE_OVERVIEW_WELCOME',
  ORGANIZATION_CONVERTED: 'ORGANIZATION_CONVERTED',
} as const;
