export default {
  DEFAULT: '',
  CHARGE: 'CHARGE',
  INVOICE: 'INVOICE',
  RECEIPT: 'RECEIPT',
  GRANT: 'GRANT',
  FUNDING_REQUEST: 'FUNDING_REQUEST',
  SETTLEMENT: 'SETTLEMENT',
  UNCLASSIFIED: 'UNCLASSIFIED',
};
