export default {
  CHARGE: 'CHARGE',
  INVOICE: 'INVOICE',
  RECEIPT: 'RECEIPT',
  GRANT: 'GRANT',
  SETTLEMENT: 'SETTLEMENT',
  UNCLASSIFIED: 'UNCLASSIFIED',
  PLATFORM_BILLING: 'PLATFORM_BILLING',
} as const;
