export const TW_API_COLLECTIVE_SLUG =
  process.env.NODE_ENV === 'production' ? 'opencollectiveinc' : 'opencollective-host';

export const states = {
  US: [
    { key: 'AL', name: 'Alabama' },
    { key: 'AK', name: 'Alaska' },
    { key: 'AZ', name: 'Arizona' },
    { key: 'AR', name: 'Arkansas' },
    { key: 'CA', name: 'California' },
    { key: 'CO', name: 'Colorado' },
    { key: 'CT', name: 'Connecticut' },
    { key: 'DE', name: 'Delaware' },
    { key: 'FL', name: 'Florida' },
    { key: 'GA', name: 'Georgia' },
    { key: 'HI', name: 'Hawaii' },
    { key: 'ID', name: 'Idaho' },
    { key: 'IL', name: 'Illinois' },
    { key: 'IN', name: 'Indiana' },
    { key: 'IA', name: 'Iowa' },
    { key: 'KS', name: 'Kansas' },
    { key: 'KY', name: 'Kentucky' },
    { key: 'LA', name: 'Louisiana' },
    { key: 'ME', name: 'Maine' },
    { key: 'MD', name: 'Maryland' },
    { key: 'MA', name: 'Massachusetts' },
    { key: 'MI', name: 'Michigan' },
    { key: 'MN', name: 'Minnesota' },
    { key: 'MS', name: 'Mississippi' },
    { key: 'MO', name: 'Missouri' },
    { key: 'MT', name: 'Montana' },
    { key: 'NE', name: 'Nebraska' },
    { key: 'NV', name: 'Nevada' },
    { key: 'NH', name: 'New Hampshire' },
    { key: 'NJ', name: 'New Jersey' },
    { key: 'NM', name: 'New Mexico' },
    { key: 'NY', name: 'New York' },
    { key: 'NC', name: 'North Carolina' },
    { key: 'ND', name: 'North Dakota' },
    { key: 'OH', name: 'Ohio' },
    { key: 'OK', name: 'Oklahoma' },
    { key: 'OR', name: 'Oregon' },
    { key: 'PA', name: 'Pennsylvania' },
    { key: 'RI', name: 'Rhode Island' },
    { key: 'SC', name: 'South Carolina' },
    { key: 'SD', name: 'South Dakota' },
    { key: 'TN', name: 'Tennessee' },
    { key: 'TX', name: 'Texas' },
    { key: 'UT', name: 'Utah' },
    { key: 'VT', name: 'Vermont' },
    { key: 'VA', name: 'Virginia' },
    { key: 'WA', name: 'Washington' },
    { key: 'WV', name: 'West Virginia' },
    { key: 'WI', name: 'Wisconsin' },
    { key: 'WY', name: 'Wyoming' },
    { key: 'DC', name: 'District of Columbia' },
    { key: 'GU', name: 'Guam' },
    { key: 'MP', name: 'Northern Mariana Islands' },
    { key: 'VI', name: 'Virgin Islands' },
  ],
  CA: [
    { key: 'AB', name: 'Alberta' },
    { key: 'BC', name: 'British Columbia' },
    { key: 'MB', name: 'Manitoba' },
    { key: 'NB', name: 'New Brunswick' },
    { key: 'NL', name: 'Newfoundland and Labrador' },
    { key: 'NS', name: 'Nova Scotia' },
    { key: 'NT', name: 'Northwest Territories' },
    { key: 'NU', name: 'Nunavut' },
    { key: 'ON', name: 'Ontario' },
    { key: 'PE', name: 'Prince Edward Island' },
    { key: 'QC', name: 'Quebec' },
    { key: 'SK', name: 'Saskatchewan' },
    { key: 'YT', name: 'Yukon' },
  ],
  AU: [
    { key: 'ACT', name: 'Australian Capital Territory' },
    { key: 'NSW', name: 'New South Wales' },
    { key: 'NT', name: 'Northern Territory' },
    { key: 'QLD', name: 'Queensland' },
    { key: 'SA', name: 'South Australia' },
    { key: 'TAS', name: 'Tasmania' },
    { key: 'VIC', name: 'Victoria' },
    { key: 'WA', name: 'Western Australia' },
  ],
  BR: [
    { key: 'AC', name: 'Acre' },
    { key: 'AL', name: 'Alagoas' },
    { key: 'AM', name: 'Amazonas' },
    { key: 'AP', name: 'Amapá' },
    { key: 'BA', name: 'Bahia' },
    { key: 'CE', name: 'Ceará' },
    { key: 'DF', name: 'Distrito Federal' },
    { key: 'ES', name: 'Espírito Santo' },
    { key: 'GO', name: 'Goiás' },
    { key: 'MA', name: 'Maranhão' },
    { key: 'MT', name: 'Mato Grosso' },
    { key: 'MS', name: 'Mato Grosso do Sul' },
    { key: 'MG', name: 'Minas Gerais' },
    { key: 'PA', name: 'Pará' },
    { key: 'PB', name: 'Paraíba' },
    { key: 'PR', name: 'Paraná' },
    { key: 'PE', name: 'Pernambuco' },
    { key: 'PI', name: 'Piauí' },
    { key: 'RJ', name: 'Rio de Janeiro' },
    { key: 'RN', name: 'Rio Grande do Norte' },
    { key: 'RO', name: 'Rondônia' },
    { key: 'RS', name: 'Rio Grande do Sul' },
    { key: 'RR', name: 'Roraima' },
    { key: 'SC', name: 'Santa Catarina' },
    { key: 'SE', name: 'Sergipe' },
    { key: 'SP', name: 'São Paulo' },
    { key: 'TO', name: 'Tocantins' },
  ],
};
