// Generated by Cypress Author on 2026-10-01; uses the repository's Jest component test runner.
import React from 'react';
import type { Operation } from '@apollo/client';
import { ApolloClient, ApolloLink, ApolloProvider, InMemoryCache, Observable } from '@apollo/client';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { Kind, visit } from 'graphql';
import { IntlProvider } from 'react-intl';
import { ThemeProvider } from 'styled-components';

import type { Expense, ExpensePayoutMethodFormMethodFieldsFragment } from '../../lib/graphql/types/v2/graphql';
import { PayoutMethodType } from '../../lib/graphql/types/v2/graphql';
import theme from '../../lib/theme';

import { ModalProvider } from '../ModalContext';
import { TooltipProvider } from '../ui/Tooltip';

import EditExpenseDialog from './EditExpenseDialog';

// Radix Select uses pointer capture, which JSDOM does not implement.
beforeAll(() => {
  HTMLElement.prototype.hasPointerCapture = () => false;
});

const loggedInUser = {
  collective: { slug: 'payee' },
  isAdminOfCollective: account => Boolean(account?.isAdmin),
  hasPreviewFeatureEnabled: () => false,
};

jest.mock('../../lib/hooks/useLoggedInUser', () => ({
  __esModule: true,
  default: () => ({ LoggedInUser: loggedInUser }),
}));

const payoutMethod = (id: string, name: string): ExpensePayoutMethodFormMethodFieldsFragment => ({
  __typename: 'PayoutMethod',
  id,
  type: PayoutMethodType.OTHER,
  name,
  data: { currency: 'EUR', content: name },
  isSaved: true,
  canBeEdited: false,
  canBeDeleted: false,
  isVerified: false,
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
});

function createScenario({ crossHost = false, sameHost = false } = {}) {
  const methods = [payoutMethod('pm-current', 'Current method'), payoutMethod('pm-next', 'Replacement method')];
  if (crossHost || sameHost) {
    methods.forEach(method => {
      method.type = PayoutMethodType.BANK_ACCOUNT;
      method.data = { currency: 'EUR', content: method.name, accountHolderName: 'Recipient host' };
    });
  }
  const host = {
    __typename: 'Host',
    id: 'payer-host',
    slug: 'payer-host',
    name: 'Payer host',
    currency: 'EUR',
    isAdmin: false,
    supportedPayoutMethods: ['OTHER', 'BANK_ACCOUNT', 'ACCOUNT_BALANCE', 'CREDIT_CARD'],
    features: { PAYPAL_CONNECT: 'DISABLED' },
    policies: {},
    accountingCategories: { nodes: [] },
    transferwise: { id: 'wise', availableCurrencies: ['EUR'] },
  };
  const recipientHost = {
    ...host,
    id: 'recipient-host',
    slug: 'recipient-host',
    name: 'Recipient host',
    isTrustedHost: true,
    isAdmin: true,
    isActive: true,
    type: 'ORGANIZATION',
    childrenAccounts: { nodes: [] },
    payoutMethods: methods,
  };
  const payee = {
    __typename: crossHost || sameHost ? 'Collective' : 'Individual',
    id: 'payee',
    slug: 'payee',
    type: crossHost || sameHost ? 'COLLECTIVE' : 'USER',
    name: 'Payee',
    legalName: 'Payee',
    isAdmin: !crossHost,
    isActive: true,
    location: { country: 'FR' },
    payoutMethods: crossHost ? [payoutMethod('pm-payee', 'Payee method')] : methods,
    ...((crossHost || sameHost) && { host: sameHost ? host : recipientHost }),
  };
  const account = {
    __typename: 'Collective',
    id: 'payer',
    slug: 'payer',
    name: 'Payer',
    type: 'COLLECTIVE',
    currency: 'EUR',
    host,
    policies: {},
    supportedExpenseTypes: ['INVOICE', 'RECEIPT'],
  };
  const expense = {
    __typename: 'Expense',
    id: 'expense-1',
    legacyId: 1,
    status: 'APPROVED',
    type: 'INVOICE',
    description: 'Travel invoice',
    currency: 'EUR',
    account,
    payee,
    payeeLocation: { country: 'FR', address: 'Original address' },
    payoutMethod: methods[0],
    taxes: [{ type: 'VAT', rate: 0.2, idNumber: 'FR40303265045' }],
    // An old rate forces the full expense form to refresh rates unnecessarily.
    items: [
      {
        id: 'item-1',
        description: 'Train ticket',
        incurredAt: '2026-01-10T00:00:00Z',
        amount: {
          valueInCents: 10000,
          currency: 'USD',
          exchangeRate: {
            value: 0.9,
            source: 'OPENCOLLECTIVE',
            fromCurrency: 'USD',
            toCurrency: 'EUR',
            date: '2026-01-01T00:00:00Z',
          },
        },
      },
      {
        id: 'item-2',
        description: 'Hotel',
        incurredAt: '2026-01-10T00:00:00Z',
        amount: { valueInCents: 5000, currency: 'EUR' },
      },
    ],
    attachedFiles: [],
    lockedFields: [],
    submitter: { id: 'submitter', slug: 'payee' },
  };
  const loggedInAccount = {
    ...payee,
    __typename: 'Individual',
    adminMemberships: { nodes: crossHost ? [{ account: recipientHost }] : [] },
  };
  return { expense, account, payee, loggedInAccount };
}

async function openDialog(scenario = createScenario()) {
  const operations: Operation[] = [];
  const client = new ApolloClient({
    cache: new InMemoryCache(),
    // Exercise real hooks and request variables without requiring a running API.
    defaultOptions: {
      query: { fetchPolicy: 'no-cache' },
      watchQuery: { fetchPolicy: 'no-cache' },
      mutate: { fetchPolicy: 'no-cache' },
    },
    link: new ApolloLink(operation => {
      operations.push(operation);
      return new Observable(observer => {
        if (operation.operationName === 'DeletePayoutMethod') {
          scenario.payee.payoutMethods = scenario.payee.payoutMethods.filter(
            method => method.id !== operation.variables.payoutMethodId,
          );
          observer.next({ data: { removePayoutMethod: { id: operation.variables.payoutMethodId } } });
          observer.complete();
          return;
        }
        const data =
          operation.operationName === 'ExpenseFormExchangeRates'
            ? {
                currencyExchangeRate: [
                  {
                    value: 0.95,
                    source: 'OPENCOLLECTIVE',
                    fromCurrency: 'USD',
                    toCurrency: 'EUR',
                    date: '2026-01-10T00:00:00Z',
                  },
                ],
              }
            : operation.operationName === 'EditExpense'
              ? {
                  editExpense: {
                    ...scenario.expense,
                    payoutMethod: { id: operation.variables.expense.payoutMethod.id },
                  },
                }
              : { ...scenario, recentlySubmittedExpenses: { nodes: [] }, submitter: scenario.expense.submitter };
        // Each HTTP response supplies fresh objects; refetches must not reuse mutable fixtures.
        observer.next({ data: JSON.parse(JSON.stringify(data)) });
        observer.complete();
      });
    }),
  });
  const user = userEvent.setup();
  render(
    <ApolloProvider client={client}>
      <IntlProvider locale="en">
        <ThemeProvider theme={theme}>
          <TooltipProvider>
            <ModalProvider>
              <EditExpenseDialog
                expense={scenario.expense as unknown as Expense}
                field="payoutMethod"
                title="Edit payout method"
                trigger={<button>Edit payout method</button>}
                showTriggerTooltip={false}
              />
            </ModalProvider>
          </TooltipProvider>
        </ThemeProvider>
      </IntlProvider>
    </ApolloProvider>,
  );
  await user.click(screen.getByRole('button', { name: 'Edit payout method' }));
  await waitFor(() => expect(screen.getByRole('button', { name: 'Save' })).toBeEnabled());
  return { user, operations };
}

describe('editing an expense payout method', () => {
  it('opens with the current selection using one scoped request and no exchange rate requests', async () => {
    const { user, operations } = await openDialog();
    expect(await screen.findByRole('radio', { name: /Current method/ })).toBeChecked();
    await user.click(await screen.findByRole('radio', { name: /Replacement method/ }));
    await waitFor(() => expect(screen.getByRole('radio', { name: /Replacement method/ })).toBeChecked());
    expect(operations.map(operation => operation.operationName)).toHaveLength(1);
    expect(operations[0].variables).toEqual({ accountSlug: 'payer', payeeSlug: 'payee' });

    const fields: string[] = [];
    visit(operations[0].query, {
      [Kind.FIELD]: node => {
        fields.push(node.name.value);
      },
    });
    expect(fields).not.toContain('expenses');
    expect(fields).not.toContain('items');
    expect(fields).not.toContain('currencyExchangeRate');
  });

  it('saves only the selected payout method and expense ID', async () => {
    const { user, operations } = await openDialog();
    await user.click(await screen.findByRole('radio', { name: /Replacement method/ }));
    await user.click(screen.getByRole('button', { name: 'Save' }));
    await waitFor(() => expect(operations.some(operation => operation.operationName === 'EditExpense')).toBe(true));
    expect(operations.find(operation => operation.operationName === 'EditExpense').variables.expense).toEqual({
      id: 'expense-1',
      payoutMethod: { id: 'pm-next' },
    });
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
  });

  it('lets a recipient host admin select the host payout methods for an expense between hosts', async () => {
    const { user, operations } = await openDialog(createScenario({ crossHost: true }));
    expect(await screen.findByText(/Pick a Payout Method from the recipient Host/)).toBeInTheDocument();
    expect(await screen.findByRole('radio', { name: /Current method/ })).toBeChecked();
    expect(screen.queryByRole('radio', { name: /Payee method/ })).not.toBeInTheDocument();
    await user.click(screen.getByRole('radio', { name: /Replacement method/ }));
    await user.click(screen.getByRole('button', { name: 'Save' }));
    await waitFor(() => expect(operations.some(operation => operation.operationName === 'EditExpense')).toBe(true));
    expect(operations.find(operation => operation.operationName === 'EditExpense').variables.expense).toEqual({
      id: 'expense-1',
      payoutMethod: { id: 'pm-next' },
    });
  });

  it('preserves an unsaved current payout method that is absent from the account methods', async () => {
    const scenario = createScenario();
    scenario.expense.payoutMethod.isSaved = false;
    scenario.payee.payoutMethods = scenario.payee.payoutMethods.filter(method => method.id !== 'pm-current');
    const { user, operations } = await openDialog(scenario);
    expect(await screen.findByRole('radio', { name: /Current method/ })).toBeChecked();
    await user.click(screen.getByRole('button', { name: 'Save' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    expect(operations.find(operation => operation.operationName === 'EditExpense').variables.expense).toEqual({
      id: 'expense-1',
      payoutMethod: { id: 'pm-current' },
    });
  });

  it('offers an account balance transfer for accounts under the same host', async () => {
    const { user, operations } = await openDialog(createScenario({ sameHost: true }));
    const balanceMethod = await screen.findByRole('radio', { name: /Account balance/i });
    expect(screen.queryByRole('radio', { name: /Replacement method/ })).not.toBeInTheDocument();
    expect(screen.queryByRole('radio', { name: /New payout method/ })).not.toBeInTheDocument();
    await user.click(balanceMethod);
    await user.click(screen.getByRole('button', { name: 'Save' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    expect(operations.find(operation => operation.operationName === 'EditExpense').variables.expense).toEqual({
      id: 'expense-1',
      payoutMethod: { type: 'ACCOUNT_BALANCE', data: {} },
    });
  });

  it('removes the original method after deletion while another method is selected', async () => {
    const scenario = createScenario();
    scenario.expense.payoutMethod.canBeEdited = true;
    scenario.expense.payoutMethod.canBeDeleted = true;
    const { user, operations } = await openDialog(scenario);
    await user.click(await screen.findByRole('radio', { name: /Replacement method/ }));
    const originalMethod = screen.getByRole('radio', { name: /Current method/ });
    await user.click(within(originalMethod).getByRole('button', { name: 'Remove payout method' }));
    await user.click(await screen.findByRole('button', { name: 'Delete Payout Method' }));
    await waitFor(() =>
      expect(operations.filter(operation => operation.operationName === 'ExpensePayoutMethodForm')).toHaveLength(2),
    );
    await waitFor(() => expect(screen.queryByRole('radio', { name: /Current method/ })).not.toBeInTheDocument());
    expect(screen.getByRole('radio', { name: /Replacement method/ })).toBeChecked();
    const queries = operations.filter(operation => operation.operationName === 'ExpensePayoutMethodForm');
    expect(queries[1].variables).toEqual(queries[0].variables);
    expect(operations.map(operation => operation.operationName)).not.toContain('ExpenseFormExchangeRates');
  });

  it('validates and saves a new payout method without including expense amounts', async () => {
    const { user, operations } = await openDialog();
    await user.click(await screen.findByRole('radio', { name: /New payout method/ }));
    await user.click(screen.getAllByRole('button', { name: 'Save' }).at(-1));
    expect(await screen.findByText('Required')).toBeInTheDocument();
    expect(operations.map(operation => operation.operationName)).not.toContain('EditExpense');

    await user.click(screen.getByRole('combobox', { name: /Choose a payout method/ }));
    await user.click(await screen.findByRole('option', { name: 'Other' }));
    await user.click(screen.getByRole('combobox', { name: 'Currency' }));
    await user.click(await screen.findByRole('option', { name: /EUR/ }));
    await user.type(screen.getByRole('textbox', { name: 'Info' }), 'Pay by check');
    await user.click(screen.getAllByRole('button', { name: 'Save' }).at(-1));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    expect(operations.find(operation => operation.operationName === 'EditExpense').variables.expense).toEqual({
      id: 'expense-1',
      payoutMethod: { type: 'OTHER', data: { currency: 'EUR', content: 'Pay by check' }, isSaved: false },
    });
    expect(operations).toHaveLength(2);
  });

  it('keeps the existing account balance method selected without adding a duplicate transfer option', async () => {
    const scenario = createScenario({ sameHost: true });
    scenario.expense.payoutMethod.type = PayoutMethodType.ACCOUNT_BALANCE;
    scenario.expense.payoutMethod.data = { currency: 'EUR' };
    scenario.expense.payoutMethod.isSaved = false;
    scenario.payee.payoutMethods = [];
    const { user, operations } = await openDialog(scenario);
    expect(await screen.findByRole('radio', { name: /Current method/ })).toBeChecked();
    expect(screen.getAllByRole('radio')).toHaveLength(1);
    await user.click(screen.getByRole('button', { name: 'Save' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    expect(operations.find(operation => operation.operationName === 'EditExpense').variables.expense).toEqual({
      id: 'expense-1',
      payoutMethod: { id: 'pm-current' },
    });
  });

  it('retains the full draft form so draft updates continue to supply their taxes and items', async () => {
    const scenario = createScenario();
    const draftScenario = {
      ...scenario,
      expense: {
        ...scenario.expense,
        status: 'DRAFT',
        draft: {
          payee: { slug: scenario.payee.slug },
          items: scenario.expense.items.map(item => ({ ...item, amountV2: item.amount })),
        },
      },
    };
    const { user, operations } = await openDialog(draftScenario);
    await user.click(await screen.findByRole('radio', { name: /Replacement method/ }));
    await user.click(screen.getByRole('button', { name: 'Save' }));
    await waitFor(() => expect(screen.queryByRole('dialog')).not.toBeInTheDocument());
    const update = operations.find(operation => operation.operationName === 'EditExpense').variables.expense;
    expect(update.payoutMethod).toEqual({ id: 'pm-next' });
    expect(update.tax).toEqual(scenario.expense.taxes);
    expect(update.items).toHaveLength(scenario.expense.items.length);
    expect(operations.map(operation => operation.operationName)).not.toContain('ExpensePayoutMethodForm');
  });
});
