import { has, isNil } from 'lodash';
import { parseToRgb, rgbToColorString } from 'polished';

import { centsAmountToFloat, floatAmountToCents } from './currency-utils';
import { parseToBoolean } from './utils';

type SimpleType = {
  type: 'string' | 'stringArray' | 'integer' | 'amount' | 'boolean' | 'color' | 'json' | 'interval';
};

type AliasType = {
  type: 'alias';
  on: string;
  modifier?: (value: any) => any;
};

type ValidTypes = SimpleType | AliasType;

export type FieldsConfig = { [key: string]: ValidTypes };

/**
 * A tool to work with URL query parameters as generated by Next Router.
 */
export default class UrlQueryHelper {
  private config: FieldsConfig;

  constructor(config: FieldsConfig) {
    this.config = config;
  }

  static Decoders = {
    /**
     * @param {string} str
     * @returns {number}
     */
    amount: (str: string) => {
      if (isNil(str) || !str.length) {
        return null;
      } else {
        const result = floatAmountToCents(parseFloat(str));
        return isNaN(result) ? null : result;
      }
    },
    /**
     * @param {string} str
     * @returns {boolean}
     */
    boolean: str => {
      return isNil(str) || !str.length ? null : parseToBoolean(str, null);
    },
    /**
     * @param {string} str
     * @returns {string}
     */
    color: str => {
      if (!str) {
        return null;
      } else if (str.match(/^(?=\d*$)(?:.{3}|.{6}|.{8})$/)) {
        return `#${str}`; // Allow hex colors to be passed without the #
      } else {
        try {
          return rgbToColorString(parseToRgb(str));
        } catch {
          // Ignore errors, will return null
        }
      }

      return null;
    },
    /**
     * @param {string} str
     * @returns {number}
     */
    integer: str => {
      if (isNil(str) || !str.length) {
        return null;
      } else {
        const result = parseInt(str);
        return isNaN(result) || !Number.isSafeInteger(result) ? null : result;
      }
    },
    /**
     * @param {string} str
     * @returns {('month'|'year')}
     */
    interval: str => {
      const cleanStr = str?.trim()?.replace(/ly$/, ''); // support for "monthly"/"yearly"
      return ['month', 'year'].includes(cleanStr) ? cleanStr : null;
    },
    /**
     * @param {string} str
     * @returns {object}
     */
    json: str => {
      try {
        return JSON.parse(str);
      } catch (err) {
        return null;
      }
    },
    /**
     * @param {string} str
     * @returns {string[]}
     */
    stringArray: str => {
      return !str ? null : str.split(',');
    },
  };

  static Encoders = {
    amount: (value: number): string => centsAmountToFloat(value)?.toString() || null,
    boolean: (value: boolean): string => (value ? 'true' : 'false'),
    integer: (value: number): string => value.toString(),
    json: (value: Record<string, unknown>): string => JSON.stringify(value),
    stringArray: (value: string[]): string => value.join(','),
  };

  /**
   * Decode a query object as provided by router.query according to `config`
   * @param {object} queryObject
   */
  decode(queryObject) {
    const result = {};
    Object.entries(this.config).forEach(([key, param]) => {
      if (!has(queryObject, key)) {
        return;
      }

      // Decode value
      const value = queryObject[key];
      const isAlias = param.type === 'alias';
      const targetKey = isAlias ? param.on : key;
      const fieldType = this.config[targetKey].type;
      const decoder = UrlQueryHelper.Decoders[fieldType];
      const decodedValue = decoder ? decoder(value) : value;
      result[targetKey] = param['modifier'] ? param['modifier'](decodedValue) : decodedValue;
    });

    return result;
  }

  /**
   * Encode the values of `queryObject` to make it safe to pass in router.push
   * @param {object} queryObject
   */
  encode(queryObject) {
    const result = {};
    Object.entries(queryObject).forEach(([key, value]) => {
      const param = this.config[key];
      if (!param) {
        return;
      }

      // Encode value
      const isAlias = param.type === 'alias';
      const targetKey = isAlias ? param.on : key;
      const fieldType = this.config[targetKey].type;
      const encoder = UrlQueryHelper.Encoders[fieldType];
      const encodedValue = encoder ? encoder(value) : value;

      // If it's an aliased field, set the value on the referenced field
      result[targetKey] = encodedValue;
    });

    return result;
  }
}
