import { writeFileSync, readFileSync } from 'fs';
import { buildSchema, introspectionFromSchema } from 'graphql';

const schemaSDL = readFileSync('./lib/graphql/schemaV2.graphql', 'utf-8');
const schema = buildSchema(schemaSDL);
const introspection = introspectionFromSchema(schema);

writeFileSync(
  './lib/graphql/tada-introspection.ts',
  `// This file is auto-generated by scripts/generate-tada-schema.ts
// Do not edit manually. Run \`npm run graphql:tada\` to regenerate.

export const introspection = ${JSON.stringify(introspection, null, 2)} as const;
`,
);

console.log('Generated lib/graphql/tada-introspection.ts');
