/**
 * Dependencies.
 */

const async = require('async');
const _ = require('lodash');
const activities = require('../constants/activities');
const utils = require('../lib/utils');

/**
 * Controller.
 */

module.exports = (app) => {

  /**
   * Internal Dependencies.
   */

  const errors = app.errors;

  const models = app.set('models');
  const PaymentMethod = models.PaymentMethod;
  const User = models.User;
  const Donation = models.Donation;
  const Activity = models.Activity;
  const Subscription = models.Subscription;
  const Group = models.Group;

  const transactions = require('./transactions')(app);
  const constants = require('../constants/transactions');

  const stripe = (req, res, next) => {
    const body = req.body;
    const isProduction = app.set('env') === 'production';

    // Stripe send test events to production as well
    // don't do anything if the event is not livemode
    if (isProduction && !body.livemode) {
      return res.sendStatus(200);
    }

    async.auto({
      fetchEvent: (cb) => {

        /**
         * We check the event on stripe to be sure we don't get a fake event from
         * someone else
         */
        app.stripe.events.retrieve(body.id, {
          stripe_account: body.user_id
        })
        .then(event => {
          if (event.type !== 'invoice.payment_succeeded') {
            return cb(new errors.BadRequest('Wrong event type received'));
          }

          const invoice = event.data.object;
          const invoiceLineItems = invoice.lines.data;
          const stripeSubscription = _.find(invoiceLineItems, { type: 'subscription' });

          const planId = utils.planId(stripeSubscription.plan);

          /**
           * With connected accounts we get all the events of the account
           * We will return a 200 if the plan is not in our format (not generated by us)
           * Example: Ruby together has a subscription model outside of us.
           * https://dashboard.stripe.com/acct_15avvkAcWgwn5pBt/events/evt_17oYejAcWgwn5pBtRo5gRiyY
           */
          if (planId !== stripeSubscription.plan.id) {
            return res.sendStatus(200);
          }

          cb(null, {
            event,
            stripeSubscription
          });
        })
        .catch(cb);
      },

      createActivity: ['fetchEvent', (cb, results) => {
        // Only save activity when the event is valid
        Activity.create({
          type: activities.WEBHOOK_STRIPE_RECEIVED,
          data: {
            event: results.fetchEvent.event,
            stripeAccount: body.user_id,
            eventId: body.id,
            dashboardUrl: `https://dashboard.stripe.com/${body.user_id}/events/${body.id}`
          }
        })
        .done(cb);
      }],

      fetchDonation: ['createActivity', (cb, results) => {
        const stripeSubscriptionId = results.fetchEvent.stripeSubscription.id;

        Donation.findOne({
          include: [
            { model: Group },
            { model: User },
            { model: Subscription, where: { stripeSubscriptionId } }
          ]
        })
        .then((transaction) => {
          /**
           * Stripe doesn't make a difference between development, test, staging
           * environments. If we get a webhook from another env,
           * `transaction.Subscription.stripeSubscriptionId`
           * will not be found and throw an error. Stripe will retry to send the webhook
           * if it doesn't get a 2XX status code.
           * For non-production environments, we will simply return 200 to avoid
           * the retry on Stripe side (and the email from Stripe support).
           */
          if (!transaction && !isProduction) {
            return res.sendStatus(200);
          }

          if (!transaction) {
            return cb(new errors.BadRequest('Transaction not found: unknown subscription id'));
          }

          return cb(null, transaction);
        })
        .catch(cb)
      }],

      fetchPaymentMethod: ['fetchDonation', (cb, results) => {
        const user = results.fetchDonation.user;
        const customer = results.fetchEvent.event.data.object.customer;


        PaymentMethod.findOne({
          where: {
            customerId: customer,
            userId: user.id
          }
        })
        .then((paymentMethod) => {
          if (!paymentMethod) {
            return cb(new errors.BadRequest('PaymentMethod not found: unknown customer'));
          }
          return cb(null, paymentMethod);
        })
        .catch(cb)
      }],

      createTransaction: ['fetchPaymentMethod', (cb, results) => {
        const donation = results.fetchTransaction;
        const subscription = donation.Subscription;
        const stripeSubscription = results.fetchEvent.stripeSubscription;
        const user = donation.User || {};
        const group = donation.Group || {};
        const paymentMethod = results.fetchPaymentMethod;

        // If the subscription is not active, we will just update the already existing one
        // We only use pending subscriptions for the first subscription invoice
        if (!subscription.isActive) {
          return subscription.activate()
            .then(subscription => {
              return Activity.create({
                type: activities.SUBSCRIPTION_CONFIRMED,
                data: {
                  event: results.fetchEvent.event,
                  group: results.fetchTransaction.Group,
                  user: results.fetchTransaction.User,
                  transaction: results.fetchTransaction,
                  subscription
                }
              });
            })
            .then(() => cb())
            .catch(cb);
        }

        // Now we record a new transaction
        const newTransaction = {
          type: constants.type.DONATION,
          DonationId: donation.id,
          amount: stripeSubscription.amount / 100,
          currency: stripeSubscription.currency,
          paidby: user && user.id, // remove #postmigration
          description: 'Recurring subscription', // remove #postmigration
          tags: ['Donation'], // remove #postmigration
          approved: true, // remove #postmigration
          interval: transaction.interval, // remove #postmigration
          SubscriptionId: subscription.id, // remove #postmigration
        };

        transactions._create({
          transaction: newTransaction,
          user,
          group,
          paymentMethod
        }, cb);
      }]

    }, (err) => {
      if (err) return next(err);

      /**
       * We need to return a 200 to tell stripe to not retry the webhook.
       */
      res.sendStatus(200);
    });

  };

  return {
    stripe
  };

};
