export const whiteListDomains = [
  'hush.com',
  'opayq.com',
  'mailhero.io',
  'mailinator.com',
  'sudomail.com',
  'maildrop.cc',
  'neverbox.com',
  'thrott.com',
  'gmial.com',
  'sharklasers.com',
  'spamgourmet.com',
  'guerrillamail.com',
  'urhen.com',
  'max-mail.com',
  'daymail.life',
  'cndps.com',
  'nicemail.pro',
  'its0k.com',
  'spamex.com',
  'zebra.email',
  'byom.de',
  'yeah.net',
  'nigge.rs',
  'xoxy.net',
];

export default whiteListDomains;
