enum FEATURE {
  CONVERSATIONS = 'CONVERSATIONS',
  EXPENSES = 'EXPENSES',
  ORDER = 'ORDER',
  CONTACT_COLLECTIVE = 'CONTACT_COLLECTIVE',
  CREATE_COLLECTIVE = 'CREATE_COLLECTIVE',
}

export default FEATURE;
